image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci
platform: linux
inputs:
  - name: grootfs-bench-release
  - name: grootfs-bench-git-repo
outputs:
  - name: bumped-release-git
run:
  path: grootfs-bench-release/ci/scripts/bump-grootfs-bench-release.sh
  user: root
