image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-bench-release-ci
platform: linux
inputs:
  - name: grootfs-bench-release-version
  - name: grootfs-bench-release
outputs:
  - name: bosh-release
run:
  path: grootfs-bench-release/ci/scripts/create-grootfs-bench-release.sh
