---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci
    tag: latest

inputs:
  - name: grootfs-bench-release

params:
  BOSH_TARGET:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_DEPLOYMENT:
  BOSH_CERTIFICATES:
  ERRAND_NAME:
  DATADOG_API_KEY:
  DATADOG_APPLICATION_KEY:

run:
  path: grootfs-bench-release/ci/scripts/performance-tests.sh
  user: root
