---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci
    tag: latest

inputs:
  - name: grootfs-ci-secrets
  - name: grootfs-bench-release
  - name: grootfs-release-develop
  - name: manifests

params:
  BOSH_TARGET:
  BOSH_USER:
  BOSH_PASSWORD:
  BOSH_MANIFEST:
  ERRAND_NAME:
  DATADOG_API_KEY:
  DATADOG_APPLICATION_KEY:

run:
  path: grootfs-bench-release/ci/scripts/performance-tests.sh
  user: root
