---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci
    tag: latest

inputs:
  - name: grootfs-ci-secrets
  - name: grootfs-bench-release
  - name: grootfs-release-develop

params:
  DATADOG_API_KEY:
  DATADOG_APPLICATION_KEY:

run:
  path: grootfs-bench-release/ci/scripts/publish-commit-event.sh
  user: root
